import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <h2>Test</h2>
          <Link href="/signup">
            <a>Signup</a>
          </Link>
        </Layout>
      </main>

    </>
  )
}
